/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import modelo.*;
/**
 *
 * @author ONYX
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    public static ListaViajes l1 = new ListaViajes(6);
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocation(350, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        opt1 = new javax.swing.JMenu();
        optAgregarViaje = new javax.swing.JMenuItem();
        optBuscarViaje = new javax.swing.JMenuItem();
        opt2 = new javax.swing.JMenu();
        optViajesHospedaje = new javax.swing.JMenuItem();
        optViajesAlimento = new javax.swing.JMenuItem();
        optViajesTransporte = new javax.swing.JMenuItem();
        optVehiculoPorViaje = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Freebird");

        jDesktopPane1.setAutoscrolls(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/fondo.jpg"))); // NOI18N

        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        opt1.setText("Viaje");

        optAgregarViaje.setText("Agregar viaje");
        optAgregarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAgregarViajeActionPerformed(evt);
            }
        });
        opt1.add(optAgregarViaje);

        optBuscarViaje.setText("Buscar viaje");
        optBuscarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optBuscarViajeActionPerformed(evt);
            }
        });
        opt1.add(optBuscarViaje);

        jMenuBar1.add(opt1);

        opt2.setText("Consultar");

        optViajesHospedaje.setText("Viajes que requirieron de hospedaje");
        optViajesHospedaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optViajesHospedajeActionPerformed(evt);
            }
        });
        opt2.add(optViajesHospedaje);

        optViajesAlimento.setText("Viajes que requirieron pago para alimentacion");
        optViajesAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optViajesAlimentoActionPerformed(evt);
            }
        });
        opt2.add(optViajesAlimento);

        optViajesTransporte.setText("Viajes que utilizaron el transporte de la empresa");
        optViajesTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optViajesTransporteActionPerformed(evt);
            }
        });
        opt2.add(optViajesTransporte);

        optVehiculoPorViaje.setText("Viajes realizados por cada vehiculo");
        optVehiculoPorViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optVehiculoPorViajeActionPerformed(evt);
            }
        });
        opt2.add(optVehiculoPorViaje);

        jMenuBar1.add(opt2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optAgregarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAgregarViajeActionPerformed
        // TODO add your handling code here:
        FrmAgregarViaje formularioAgregarViaje = new FrmAgregarViaje(l1);
        jDesktopPane1.add(formularioAgregarViaje);
        formularioAgregarViaje.setVisible(true);
    }//GEN-LAST:event_optAgregarViajeActionPerformed

    private void optViajesTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optViajesTransporteActionPerformed
        // TODO add your handling code here:
        FrmViajesTransporte formularioViajesTransporte = new FrmViajesTransporte(l1);
        jDesktopPane1.add(formularioViajesTransporte);
        formularioViajesTransporte.setVisible(true);
    }//GEN-LAST:event_optViajesTransporteActionPerformed

    private void optViajesAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optViajesAlimentoActionPerformed
        // TODO add your handling code here:
        FrmViajesAlimento formularioViajesAlimento = new FrmViajesAlimento(l1);
        jDesktopPane1.add(formularioViajesAlimento);
        formularioViajesAlimento.setVisible(true);
    }//GEN-LAST:event_optViajesAlimentoActionPerformed

    private void optViajesHospedajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optViajesHospedajeActionPerformed
        // TODO add your handling code here:
        FrmViajesHospedaje formularioViajesHospedaje = new FrmViajesHospedaje(l1);
        jDesktopPane1.add(formularioViajesHospedaje);
        formularioViajesHospedaje.setVisible(true);
    }//GEN-LAST:event_optViajesHospedajeActionPerformed

    private void optVehiculoPorViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optVehiculoPorViajeActionPerformed
        // TODO add your handling code here:
        FrmViajesVehiculo formularioViajesVehiculo = new FrmViajesVehiculo(l1);
        jDesktopPane1.add(formularioViajesVehiculo);
        formularioViajesVehiculo.setVisible(true);
    }//GEN-LAST:event_optVehiculoPorViajeActionPerformed

    private void optBuscarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optBuscarViajeActionPerformed
        // TODO add your handling code here:
        FrmBuscarViaje busqueda = new FrmBuscarViaje(l1);
        jDesktopPane1.add(busqueda);
        busqueda.setVisible(true);
    }//GEN-LAST:event_optBuscarViajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu opt1;
    private javax.swing.JMenu opt2;
    private javax.swing.JMenuItem optAgregarViaje;
    private javax.swing.JMenuItem optBuscarViaje;
    private javax.swing.JMenuItem optVehiculoPorViaje;
    private javax.swing.JMenuItem optViajesAlimento;
    private javax.swing.JMenuItem optViajesHospedaje;
    private javax.swing.JMenuItem optViajesTransporte;
    // End of variables declaration//GEN-END:variables
}
